// DemoPanel.jsx
import './DemoPanel.css';

export default function DemoPanel() {
  return (
    <section className="demo section-wrap" id="demo">

      <div className="section-header reveal">
        <div>
          <span className="section-tag">See it work</span>
          <h2 className="section-title">From paper to code,<br /><em>nothing lost.</em></h2>
        </div>
        <p className="section-note">Every equation, figure, and citation preserved with precision.</p>
      </div>

      <div className="demo-panels reveal d1">

        {/* PDF */}
        <div className="demo-pane">
          <div className="demo-pane-bar">
            <span className="pane-label">Original PDF</span>
            <span className="pane-badge">Input</span>
          </div>
          <div className="demo-pdf">
            <p className="pdf-title">Attention Is All You Need — Vaswani et al.</p>
            <p className="pdf-tag">Abstract</p>
            <div className="pdf-lines">
              <span className="pl w100"/><span className="pl w90"/><span className="pl w85"/><span className="pl w75"/>
            </div>
            <p className="pdf-prose">
              The dominant sequence transduction models contain complex recurrent networks. The attention function maps query&nbsp;
              <span className="pdf-eq">Q, K, V</span> as:
            </p>
            <div className="pdf-eq-block">
              Attention(Q,K,V) = softmax( QK<sup>⊤</sup> / √d_k ) V
            </div>
            <div className="pdf-lines" style={{marginTop:'0.8rem'}}>
              <span className="pl w100"/><span className="pl w80"/><span className="pl w60"/>
            </div>
          </div>
        </div>

        {/* Arrow */}
        <div className="demo-arrow" aria-hidden="true">
          <svg viewBox="0 0 20 20" fill="none">
            <path d="M4 10h12M12 6l4 4-4 4" stroke="#FAF7F2" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
          </svg>
        </div>

        {/* LaTeX */}
        <div className="demo-pane">
          <div className="demo-pane-bar">
            <span className="pane-label">LaTeX Output</span>
            <span className="pane-badge pane-badge--ok">Ready to compile</span>
          </div>
          <div className="demo-latex">
            <p><span className="lx-c">% Generated by Glyphra</span></p>
            <p><span className="lx-k">\documentclass</span><span className="lx-b">[</span><span className="lx-a">12pt</span><span className="lx-b">]&#123;</span><span className="lx-a">article</span><span className="lx-b">&#125;</span></p>
            <p><span className="lx-k">\usepackage</span><span className="lx-b">&#123;</span><span className="lx-a">amsmath</span><span className="lx-b">&#125;</span></p>
            <br/>
            <p><span className="lx-k">\begin</span><span className="lx-b">&#123;</span><span className="lx-a">document</span><span className="lx-b">&#125;</span></p>
            <p><span className="lx-k">\section*</span><span className="lx-b">&#123;</span><span className="lx-a">Abstract</span><span className="lx-b">&#125;</span></p>
            <p><span className="lx-t">The dominant sequence...</span></p>
            <br/>
            <p><span className="lx-k">\begin</span><span className="lx-b">&#123;</span><span className="lx-a">equation</span><span className="lx-b">&#125;</span></p>
            <p>&nbsp;&nbsp;<span className="lx-m">\text&#123;Attention&#125;(Q,K,V) =</span></p>
            <p>&nbsp;&nbsp;<span className="lx-m">\text&#123;softmax&#125;\!\left(</span></p>
            <p>&nbsp;&nbsp;&nbsp;&nbsp;<span className="lx-m">\frac&#123;QK^\top&#125;&#123;\sqrt&#123;d_k&#125;&#125;</span></p>
            <p>&nbsp;&nbsp;<span className="lx-b">\right)</span><span className="lx-m">V</span></p>
            <p><span className="lx-k">\end</span><span className="lx-b">&#123;</span><span className="lx-a">equation</span><span className="lx-b">&#125;</span></p>
          </div>
        </div>

      </div>
    </section>
  );
}
