// pages/Workspace.jsx — Three-panel LaTeX workspace

import { useState, useEffect } from 'react';
import './Workspace.css';

const TEMPLATES = ['article','IEEEtran','ACM','Nature','beamer'];

const PLACEHOLDER = `% Generated by Glyphra — glyphra.io
\\documentclass[12pt]{article}
\\usepackage{amsmath, amssymb}
\\usepackage{graphicx}
\\usepackage{cite}
\\usepackage{hyperref}

\\title{Your Paper Title}
\\author{Author Name}
\\date{\\today}

\\begin{document}

\\maketitle

\\begin{abstract}
Your abstract text will appear here after conversion.
\\end{abstract}

\\section{Introduction}
Section content generated from your uploaded PDF.

\\section{Methods}
Methodology section content here.

\\begin{equation}
  E = mc^2
\\end{equation}

\\section{Results}
Results and findings here.

\\section{Conclusion}
Conclusions here.

\\bibliographystyle{plain}
\\bibliography{references}

\\end{document}`;

export default function Workspace() {

  const [latex,    setLatex]    = useState('');
  const [filename, setFilename] = useState('document');
  const [template, setTemplate] = useState('article');
  const [copied,   setCopied]   = useState(false);

  useEffect(() => {
    const stored = sessionStorage.getItem('glyphra_result');
    if (stored) {
      const { latex: l, filename: f } = JSON.parse(stored);
      setLatex(l || PLACEHOLDER);
      setFilename(f?.replace('.pdf','') || 'document');
    } else {
      setLatex(PLACEHOLDER);
    }
  }, []);

  const handleCopy = () => {
    navigator.clipboard.writeText(latex);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([latex], { type: 'text/plain' });
    const url  = URL.createObjectURL(blob);
    const a    = Object.assign(document.createElement('a'), { href: url, download: `${filename}.tex` });
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleOverleaf = () => {
    window.open(`https://www.overleaf.com/docs?snip=${encodeURIComponent(latex)}`, '_blank', 'noopener,noreferrer');
  };

  return (
    <div className="ws">

      {/* Workspace nav */}
      <header className="ws-nav">
        <a href="/" className="ws-logo"><span>T</span>ypra<span className="ws-dot">.</span></a>
        <p className="ws-fname">{filename}.tex</p>
        <div className="ws-actions">
          <button className="ws-ghost" onClick={handleCopy}>{copied ? 'Copied!' : 'Copy'}</button>
          <button className="ws-ghost" onClick={handleDownload}>Download .tex</button>
          <button className="ws-solid" onClick={handleOverleaf}>Open in Overleaf ↗</button>
        </div>
      </header>

      {/* Three panels */}
      <div className="ws-panels">

        {/* Panel 1 — PDF */}
        <aside className="ws-panel ws-panel--pdf">
          <div className="ws-pane-hd">
            <span className="ws-pane-label">Original PDF</span>
          </div>
          <div className="ws-pdf-empty">
            <p>PDF preview loads here after upload</p>
          </div>
        </aside>

        {/* Panel 2 — Editor */}
        <main className="ws-panel ws-panel--editor">
          <div className="ws-pane-hd">
            <span className="ws-pane-label">LaTeX Output</span>
            <div className="ws-template-row">
              <label htmlFor="tpl" className="ws-tpl-label">Class</label>
              <select id="tpl" className="ws-select" value={template} onChange={(e) => setTemplate(e.target.value)}>
                {TEMPLATES.map((t) => <option key={t}>{t}</option>)}
              </select>
            </div>
          </div>
          <textarea
            className="ws-editor"
            value={latex}
            onChange={(e) => setLatex(e.target.value)}
            spellCheck={false}
            aria-label="LaTeX code editor"
          />
        </main>

        {/* Panel 3 — Controls */}
        <aside className="ws-panel ws-panel--ctrl">
          <div className="ws-pane-hd">
            <span className="ws-pane-label">Export</span>
          </div>
          <div className="ws-ctrl-body">

            <div className="ws-ctrl-group">
              <p className="ws-ctrl-label">Document class</p>
              <select className="ws-select ws-select--full" value={template} onChange={(e) => setTemplate(e.target.value)}>
                {TEMPLATES.map((t) => <option key={t}>{t}</option>)}
              </select>
            </div>

            <div className="ws-divider" />

            <div className="ws-ctrl-group">
              <p className="ws-ctrl-label">Download</p>
              <button className="ws-text-btn" onClick={handleDownload}>.tex file →</button>
              <button className="ws-text-btn" onClick={handleCopy}>{copied ? 'Copied!' : 'Copy to clipboard →'}</button>
            </div>

            <div className="ws-divider" />

            <div className="ws-ctrl-group">
              <p className="ws-ctrl-label">Open in editor</p>
              <button className="ws-solid ws-solid--full" onClick={handleOverleaf}>
                Open in Overleaf ↗
              </button>
            </div>

          </div>
        </aside>

      </div>

    </div>
  );
}
